spring:
  datasource:
    url: jdbc:postgresql://ep-lucky-tree-b37fehnz-pooler.c-4.ap-southeast-1.aws.neon.tech/campusconnect?sslmode=require&channel_binding=require
    username: campusconnect_owner
    password: npg_DFBkvylJ2tb6
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  sql:
    init:
      mode: always

server:
  port: 8080

app:
  jwt:
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    expiration: 86400000  # 1 day in ms

logging:
  level:
    org.springframework.security: DEBUG
